---
name: Ensure this repository stays active

on:
  schedule:
    - cron: "0 0 1 * *"
  push:

jobs:
  mantid-runner:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1

      - name: Replace credentials
        run: |
          sed -i 's/Last updated: /Last updated: $(date)/g' README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "active@stfc.ac.uk"
          git config --local user.name "Most Active User"
          git commit -am "I promise this is active"
          git push
